### PR TITLE
[compat] Remove deprecated python version (except py27)

### PR DESCRIPTION
**Pull request by Djailla**

### CODE REVIEW

**Comment by mtth** [comment]
Merged - thanks @Djailla.

**Comment by Djailla** [comment]
@mtth shall I work on remove py27 support ?

**Comment by mtth** [comment]
Let's keep it until we have a reason to remove it. We'd probably do it with a major version bump.

**Comment by Djailla** [comment]
py27 is deprecated

**Comment by mtth** [comment]
There are still quite a few users of Python 2.7; it's not acceptable to break all them.

**Pull request merged**
